name: Register specification
description: Register a new optimization model
inputs:
  token:
    description: Opvious API access token
    required: true
  sources:
    description: Glob of specification sources
    required: true
  dry-run:
    description: |
      When true, specifications will only be validated and not registered
    default: false
  tags:
    description: Comma-separated list of tag names
  domain:
    description: Opvious API domain
runs:
  using: node16
  main: dist/index.js
