name: Register specification
description: Register a new optimization model
inputs:
  token:
    description: Opvious API access token
    required: true
  sources:
    description: |
      Specification sources. This can either be a single string glob or a YAML
      list of objects (see below).

      When a single glob is passed in, each matched file will be considered a
      self-contained specification. The name of the formulation will be derived
      from the file's name by stripping the extension. The specification's
      description will be set to the file's contents.

      When a list of objects are passed in, each is expected to describe a
      single specification and should contain the following fields:

      * `name` (required), the name of the formulation
      * `sources` (required), glob of source files
      * `description` (optional), path of file to use as description

      Examples:

        # Single glob
        sources: sources/*.md

        # Multiple specifications
        sources: |
          - name: first-formulation
            sources: sources/first.md
          - name: second-formulation
            sources: sources/second/*.md
            description: sources/second/README.md
    required: true
  dry-run:
    description: |
      When true, specifications will only be validated and not registered.
    default: false
  tags:
    description: |
      Tag name(s) to apply to registered formulations. Multiple tags can be
      expressed via a YAML list. Unused in dry-run mode.

      Examples:

        # Single tag
        tags: golden

        # Multiple tags
        tags: |
          - golden
          - github
  domain:
    description: Opvious API domain
runs:
  using: node16
  main: dist/index.js
